
```

Then try out `node .` for a basic example based on the test fixtures

![hounds-simple](https://cloud.githubusercontent.com/assets/799038/19570264/41277d88-96c7-11e6-9060-83b7590c0cfb.gif)

Unleash them on the latest sites from HackerNews via `node hackerNews


language: node_js

node_js:
  - "7.2.1"

before_install:
  - node --version
  - npm --version

before_script:
  - cd examples
  - npm i
  - sleep 5

script:
  - node mdn.js

notifications:
  email:
    - paullittlebury@gmail.com