language: node_js

node_js:
  - "7.2.1"

before_install:
  - node --version
  - npm --version

before_script:
  - cd examples
  - npm i
  - sleep 5

script:
  - node mdn.js

notifications:
  email:
    - paullittlebury@gmail.com